version: '3.7'
services:
  composer:
    container_name: composer
    image: composer:latest
    restart: 'no'
    volumes:
      - ./app:/app
    command: ["install", "--ignore-platform-reqs"]

  app:
    container_name: app
    image: php:fpm-alpine
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
    links:
      - redis
      - db
    depends_on:
      - composer

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    networks:
      - backend

  db:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=84268
      - MYSQL_DATABASE=syscli
      - MYSQL_USER=syscli
      - MYSQL_PASSWORD=84268
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=syscli
      - PMA_PASSWORD=84268
      - MYSQL_ROOT_PASSWORD=84268
    links:
      - db
    ports:
      - 8080:80
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local