FROM php:fpm-alpine

RUN apk add --update-cache --no-cache \
        libxml2-dev \
    && docker-php-ext-install -j$(nproc) bcmath ctype json pdo pdo_mysql tokenizer xml \
    && apk del --no-cache libxml2-dev